name: Deploy to Production

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.docsearch/**'
      - 'README.md'
      - '.gitpod.yml'
  workflow_dispatch:

env:
  NO_INDEX: true
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: actions/cache@v4
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          
      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: npm install

      - uses: actions/cache@v4
        id: cache-build
        with:
          path: build
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Run Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build

  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install crcmod

      - name: Auth GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.RUN_PROJECT }}
          service_account: ${{ secrets.RUN_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 290.0.1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            build
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Run Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm run build
      - name: Deploy to Bucket
        run: |-
          cd build
          gsutil -m rsync -R -d . ${{ secrets.GCS_BUCKET }}
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      NO_INDEX: false

    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Auth GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.RUN_PROJECT_PROD }}
          service_account: ${{ secrets.RUN_SA_KEY_PROD }}

      - name: 'Set up Cloud SDK' 
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 290.0.1'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Install Dependencies
        run: |
          npm install
      - name: Run Build
        run: |
          npm run build
      - name: Deploy to Bucket
        run: |-
          cd build
          gsutil -m rsync -R -d . ${{ secrets.GCS_PROD_BUCKET }}
